version: "3.8"

services:
  db:
    image: mysql:5.6
    restart: on-failure
    ports:
    - "3306:3306"
    volumes:
    - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "sample"
      MYSQL_DATABASE: "accountowner"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"